# Generated by Django 2.1.2 on 2018-10-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perrofundacion',
            options={'verbose_name': 'Perro Fundacion', 'verbose_name_plural': 'Perros Fundacion'},
        ),
    ]
