# Generated by Django 2.1.2 on 2018-10-21 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrofundacion',
            name='fechaIngreso',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='perrofundacion',
            name='fechaNacimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
