# Generated by Django 2.1.2 on 2018-10-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181021_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrofundacion',
            name='fechaIngreso',
        ),
        migrations.RemoveField(
            model_name='perrofundacion',
            name='fechaNacimiento',
        ),
    ]
