# Generated by Django 2.1.2 on 2018-10-22 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181021_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrofundacion',
            name='fechaIngreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='perrofundacion',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
