# Generated by Django 2.1.2 on 2018-10-22 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181021_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaIngreso',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaNacimiento',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
