# Generated by Django 2.1.2 on 2018-10-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181021_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='perrofundacion',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero'),
        ),
    ]
