# Generated by Django 2.1.2 on 2018-10-22 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181021_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaIngreso',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Nacimiento'),
        ),
    ]
