# Generated by Django 2.1.2 on 2018-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181022_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=6),
        ),
    ]
