# Generated by Django 2.1.2 on 2018-10-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181022_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero', verbose_name='Género'),
        ),
    ]
