# Generated by Django 2.1.2 on 2018-10-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181023_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='region',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_vivienda',
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AddField(
            model_name='perrofundacion',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='{% static "core/img/adoptados"  %}'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
