# Generated by Django 2.1.2 on 2018-10-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181023_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perrofundacion',
            name='imagen',
        ),
    ]
