# Generated by Django 2.1.2 on 2018-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_perrofundacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaIngreso',
            field=models.DateField(verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='perrofundacion',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
    ]
