# Generated by Django 2.1.2 on 2018-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181024_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrofundacion',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
