# Generated by Django 2.1.2 on 2018-10-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perrofundacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='nro_region',
        ),
        migrations.DeleteModel(
            name='Tipo_vivienda',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
