# Generated by Django 2.1.2 on 2018-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181024_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
