# Generated by Django 2.1.2 on 2018-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181024_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrofundacion',
            name='imagen',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
